### ISSUE TITLE
404 not found on Sinsy-NG demos

### ISSUE THREAD

**Issue by ElonSatoshi** [GloomyGhost-MosquitoSeal/GloomyGhost-MosquitoSeal.github.io#3]
How to reproduce:

1. In Firefox, go to https://github.gloomyghost.com/Sinsy-NG/ and attempt to play the Sinsy-NG demos listed.

Expectation: Sound files will play

Reality: Nothing plays.

I also tried copying the link and playing it in `mpv`, but I got the error:

```
[ffmpeg] https: HTTP error 404 Not Found
Failed to open https://raw.githubusercontent.com/740291272/Sinsy-NG/demo/demo/e.wav.
[ytdl_hook] ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[ytdl_hook] youtube-dl failed: unexpected error ocurred
```

Maybe we could add a demo/demo/ directory to https://github.com/GloomyGhost-MosquitoSeal/Sinsy-NG

**Comment by GloomyGhost-MosquitoSeal** [comment]
sorry for that, i deleted demo branches.
